#coding:utf-8

'''
    Find the Difference
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        character = {}
        for i in s:
            if character.has_key(i):
                character[i] += 1
            else:
                character[i] = 1
        for i in t:
            if character.has_key(i) and character[i] != 0:
                character[i] -= 1
            else:
                return i

solution = Solution()
print solution.findTheDifference('2323', '23234')
print solution.findTheDifference('2323', '32232')